// Reference tag/group set from a TagJournal backup. New exports reuse these
// IDs/groups/colors so the output drops cleanly back into TagJournal.

export const REFERENCE_GROUPS = [
    { id: "sru21m5h", name: "Household", color: "#0d9aa8" },
    { id: "5ibmi4hb", name: "Health", color: "#2fa56a" },
    { id: "rl94b086", name: "Wife", color: "#6e56cf" },
    { id: "wnish3rp", name: "Mood", color: "#e5484d" },
    { id: "3rdayzbu", name: "Creative", color: "#f76b15" },
    { id: "l64k35mz", name: "Family", color: "#4f7cf7" },
    { id: "xhz0jnpw", name: "Avoid", color: "#889098" },
    { id: "ivwho5i8", name: "Friends", color: "#c9a800" },
];

export const REFERENCE_TAGS = [
    { id: "pohyiauq", name: "One Piece", groupId: "3rdayzbu", adjective: "Watched" },
    { id: "asfrih9c", name: "Date", groupId: "rl94b086" },
    { id: "i94mn5ik", name: "Cook", groupId: "sru21m5h" },
    { id: "7nyuf0cx", name: "Dishes", groupId: "sru21m5h" },
    { id: "k79auz4r", name: "Yoga", groupId: "5ibmi4hb", adjective: "practiced" },
    { id: "cv0mzs4s", name: "Massage", groupId: "5ibmi4hb", adjective: "relaxed with" },
    { id: "9cn8bb31", name: "Great", groupId: "wnish3rp", adjective: "Felt" },
    { id: "050x4tql", name: "Good", groupId: "wnish3rp", adjective: "Felt" },
    { id: "nbu555ey", name: "OK", groupId: "wnish3rp", adjective: "Felt" },
    { id: "ffgnhs4l", name: "Bad", groupId: "wnish3rp", adjective: "Felt" },
    { id: "ig27h3q4", name: "Awful", groupId: "wnish3rp", adjective: "Felt" },
    { id: "43m3plnk", name: "Dinner init", groupId: "rl94b086" },
    { id: "zfuqrgmz", name: "Laundry fold", groupId: "sru21m5h" },
    { id: "osy4fu43", name: "Laundry", groupId: "sru21m5h" },
    { id: "q5ixcpdf", name: "Plato Complete Works", groupId: "3rdayzbu", adjective: "Read" },
    { id: "2h8ansqq", name: "Organize", groupId: "sru21m5h" },
    { id: "0i9u1p6h", name: "Groceries", groupId: "sru21m5h" },
    { id: "vk1mbobv", name: "Dad", groupId: "l64k35mz", adjective: "Had a connection with" },
    { id: "pnk9pd50", name: "Mom", groupId: "l64k35mz", adjective: "Had a connection with" },
    { id: "ibbkaltm", name: "Grandma", groupId: "l64k35mz", adjective: "Had a connection with" },
    { id: "9gpy7pwd", name: "Grandpa", groupId: "l64k35mz", adjective: "Had a connection with" },
    { id: "hm58x67o", name: "Or", groupId: "l64k35mz", adjective: "Had a connection with" },
    { id: "d8jyiju3", name: "Sahar", groupId: "l64k35mz", adjective: "Had a connection with" },
    { id: "rfcpli62", name: "Shachar", groupId: "l64k35mz", adjective: "Had a connection with" },
    { id: "99e88zz7", name: "Ofek", groupId: "l64k35mz", adjective: "Had a connection with" },
    { id: "8atuea3i", name: "Yahel", groupId: "l64k35mz", adjective: "Had a connection with" },
    { id: "ankpcdk5", name: "CSS", groupId: "3rdayzbu" },
    { id: "f4vrzowk", name: "Porn", groupId: "xhz0jnpw", adjective: "Fallen pray to" },
    { id: "5hq9zwja", name: "Grunt", groupId: "xhz0jnpw" },
    { id: "kuksyrz5", name: "The Way of Ways", groupId: "3rdayzbu", adjective: "read" },
    { id: "mf8odwpt", name: "Bar Zakai", groupId: "l64k35mz", adjective: "meet with" },
    { id: "arrqax4f", name: "Maya", groupId: "ivwho5i8", adjective: "connected with" },
    { id: "lu66r6df", name: "Ofir", groupId: "ivwho5i8", adjective: "connected with" },
    { id: "7o28cgiz", name: "David", groupId: "ivwho5i8", adjective: "connected with" },
    { id: "93jroqu0", name: "Therapist", groupId: "5ibmi4hb", adjective: "had a session with" },
    { id: "iip1ppz3", name: "Gestures", groupId: "rl94b086", adjective: "Made" },
    { id: "zlx0ylj1", name: "Write", groupId: "3rdayzbu" },
    { id: "wc237twx", name: "Barber", groupId: "5ibmi4hb", adjective: "Visited" },
    { id: "qeu78frv", name: "Epoch Times", groupId: "3rdayzbu", adjective: "Read" },
    { id: "mip3es1s", name: "Sex", groupId: "rl94b086", adjective: "Had" },
    { id: "n6i2hh8t", name: "Trip", groupId: "rl94b086", adjective: "Went on" },
    { id: "cnr2yivz", name: "Shoham", groupId: "ivwho5i8", adjective: "Met" },
    { id: "1v8qmjjh", name: "Weight", groupId: "5ibmi4hb" },
    { id: "28l4djah", name: "Julia", groupId: "ivwho5i8" },
    { id: "vzss5lww", name: "Building Stories", groupId: "3rdayzbu", adjective: "Read" },
];
